name: On pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-build:
    name: Test
    uses: ./.github/workflows/workflow_test.yml

  deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    needs: [test-build]
    name: Deploy
    uses: ./.github/workflows/workflow_deploy_firebase.yml
    with:
      version: ${{ github.sha }}
      run_id: github_run_${{ github.run_id }}
      project_id: personalwebsite-d0b3c
