name: On pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-build:
    name: Test
    uses: ./.github/workflows/workflow_test.yml

  deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    needs: [test-build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONALWEBSITE_D0B3C }}'
          channelId: preview
          projectId: personalwebsite-d0b3c
