name: Run build

on: workflow_call

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Use Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NVMRC }}'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build